Fixed a camera issue in the Playground.unity scene
ArgumentNullException: Value cannot be null.
and
Can't add 'UniversalAdditionalCameraData' to SceneCamera because a 'UniversalAdditionalCameraData' is already added.